
title: SreeKrishna Swami Shethram
email: adithyan.damodaran@gmail.com
description: SOme Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sreekrishna.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
default:
  -scope:
    path: "assets/img"
  values:
    image: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
